site_name: Grupo Hedy Lamarr
site_url: https://fcte-qualidade-de-software-1.github.io/2026-1_T01_HEDY_LAMAR/
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2026-1_T01_HEDY_LAMAR
repo_name: 2026-1-Hedy-Lamarr
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  
  palette:
    # Dark Mode
    - scheme: slate
      toggle: 
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: orange
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.tabs
    - navigation.sections
    - content.code.copy
nav:
  - Início: index.md
  - Configuração: configs.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets