site_name: Grupo Hedy Lamarr
site_url: https://fcte-qualidade-de-software-1.github.io/2026-1_T01_HEDY_LAMAR/
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2026-1_T01_HEDY_LAMAR
repo_name: 2026-1-Hedy-Lamarr
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  
  palette:
    scheme: default
    primary: indigo
    accent: orange
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - content.code.copy
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/current-date.js
copyright: 'Relatório de Avaliação da Qualidade do No Fluxo UnB — Versão 1.0 — Atualizado em: <span id="current-date-br">03/06/2026</span> — Grupo Hedy Lamarr'
nav:
  - Início: index.md
  - Fase 1 - Requisitos da Avaliação:
    - 1. Propósito da Avaliação: fase1/01_proposito_da_avaliacao.md
    - 2. Requisitante e Partes Interessadas: fase1/02_requisitante_e_stakeholders.md
    - 3. Descrição do Produto de Software: fase1/03_descricao_produto.md
    - 4. Seleção e Priorização de Características: fase1/04_selecao_e_priorizacao_de_caracteristicas.md
    - 5. Modelo de Qualidade: fase1/05_modelo_de_qualidade.md
    - 6. Escopo, Profundidade e Objetos de Avaliação: fase1/06_escopo_profundidade_e_objetos_de_avaliacao.md
    - 7. ODS Relacionados: fase1/07_ods.md
  - Fase 2 - Especificação da Avaliação:
    - 1. Aplicação GQM: fase2/00_aplicacao_gqm.md
    - 2. Objetivo de Medição - Adequação Funcional: fase2/01_obj_adequacao_funcional.md
    - 3. Objetivo de Medição - Portabilidade: fase2/02_obj_portabilidade.md
  - Fase 3 - Projeção da avaliação:
    - 1. Projeção - Adequação Funcional: fase3/01_proj_AdequacaoFuncional.md 
    - 2. Projeção - Portabilidade: fase3/02_proj_Portabilidade.md
  - Fase 4 - Executação da avaliação:
    - 1. a: fase4/a.md
  - Declaração de Uso de IA: declaracao_uso_ia.md
  - Extras: 
    - Configuração do ambiente: extras/configs.md
    - Tabela de Contribuição: extras/contribuicao.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
